name: Build and deploy Node.js app to Azure Web App - fire-warden-tracking-system

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # Build React frontend
      - name: Install and build React frontend
        working-directory: ./web-app
        run: |
          npm install
          npm run build

      # Install backend dependencies
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      # Copy React build into backend folder
      - name: Copy React build to backend folder
        run: |
          rm -rf backend/web-app/build
          cp -r web-app/build backend/web-app/build

      # Zip backend folder for deployment
      - name: Zip backend folder for deployment
        run: |
          cd backend
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_33DC9B37FECB4130B383F378D3E92B3E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D45319EC148A4442855991D3AA97076B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_987490577D1A4C368F377676076514E7 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fire-warden-tracking-system'
          slot-name: 'Production'
          package: .
